stages:
    - build
    - test

build-elf:
    image: javiervarez/ate_builder:latest
    tags:
        - arm-none-eabi
        - docker
    stage: build
    script:
        - time make -j
    artifacts:
        paths: ["build"]
        expire_in: 1 week
        name: "stm32f1_fw"

unit-test:
    image: javiervarez/ate_builder:latest
    tags:
        - arm-none-eabi
        - docker
    stage: test
    script:
        - ./ci/run_unit_test.sh

system-test:
    tags:
        - arm-none-eabi
        - Logic
        - openocd
        - x86_64
    stage: test
    script:
        - ./ci/run_system_test.sh

size-monitor:
    image: javiervarez/ate_builder:latest
    tags:
        - arm-none-eabi
        - docker
    stage: test
    script:
        - ./ci/monitor_code_size.sh

lint:
    image: javiervarez/ate_builder:latest
    tags:
        - arm-none-eabi
        - docker
    stage: build
    script:
        - make lint

variables:
    GIT_SUBMODULE_STRATEGY: recursive
