stages:
    - build
    - test

build-elf:
    image: javiervarez/ate_builder:latest
    tags:
        - arm-none-eabi
        - docker
    stage: build
    script:
        - time make -j
    artifacts:
        paths: ["build"]
        expire_in: 1 week
        name: "stm32f1_fw"

unit-test:
    image: javiervarez/ate_builder:latest
    tags:
        - arm-none-eabi
        - docker
    stage: test
    script:
        - ./ci/run_unit_test.sh

system-test:
    tags:
        - arm-none-eabi
        - Logic
        - openocd
        - x86_64
    stage: test
    script:
        - ./ci/run_system_test.sh

size-monitor:
    image: javiervarez/ate_builder:latest
    tags:
        - arm-none-eabi
        - docker
    stage: test
    script:
        - ./ci/monitor_code_size.sh

lint:
    image: javiervarez/ate_builder:latest
    tags:
        - arm-none-eabi
        - docker
    stage: build
    script:
        - make lint
        - pip3 install pylint
        - pip3 install -r SystemTest/requirements.txt
        - find SystemTest/ -name *.py | xargs pylint

coverage:
    image: javiervarez/ate_builder:latest
    tags:
        - arm-none-eabi
        - docker
    stage: test
    script:
        - make TestCoverage -j
    artifacts:
        paths: ["build/coverage"]
        expire_in: 1 week
        name: "coverage"

static-analysis:
    image: javiervarez/ate_builder:latest
    tags:
        - arm-none-eabi
        - docker
    stage: test
    script:
        - ./ci/static_analysis.sh
    artifacts:
        paths: ["build/static_analysis/HTML"]
        expire_in: 1 week
        name: "static_analysis"

variables:
    GIT_SUBMODULE_STRATEGY: recursive
