stages:
    - build

build-elf:
    image: javiervarez/ate_builder:latest
    tags:
        - arm-none-eabi
    stage: build
    script:
        - time make -j
    artifacts:
        paths: ["build/stm32f1_fw.elf"]
        expire_in: 1 week
        name: "stm32f1_fw"
