name: Build and test Popcorn

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: Javier-varez/google-repo-action@v0.2
      with:
        manifest-url: 'Javier-varez/manifest'
        manifest-group: 'popcorn'
        checkout-deps: true
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1.0.4
      with:
        release: '10-2020-q4'
    - name: Install bear
      run: sudo apt install bear
    - name: Install multilib
      run: sudo apt install gcc-multilib g++-multilib
    - name: Build
      run: make -j
    - name: Build unit tests
      run: make -j tests
    - name: Run unit tests
      run: make run_tests
